FROM python:3.8
WORKDIR /app
RUN apt-get install -y python3-rpi.gpio
ENV CFLAGS="-fcommon"
RUN apt update && apt install -y mpg123
COPY requirements.txt requirements.txt
COPY requirements_phys.txt requirements_phys.txt
RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements_phys.txt
COPY . .
CMD [ "python3", "app.py"]